name: Building-Tests

on: 
  push:
    branches: [main]

jobs:
  images:
    runs-on: ubuntu-latest
    steps: 
      - name: Repo-Clone
        uses: actions/checkout@v5
      
      - name: Testing Vars
        run: |
          echo "This is ${{vars.DOCKER_USERNAME}}'s repository"
          echo "This is the PAT ${{secrets.DOCKER_PAT}}"

      - name: Docker-Login
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Docker-Build
        run: docker build -t ${{vars.DOCKER_USERNAME}}/ci-cd_test:latest .
      
      - name: Docker-Push
        run: docker push ${{ vars.DOCKER_USERNAME }}/ci-cd_test:latest
